// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpE5xaHwu_0r6O3ykMewCadB-1aW9zE4',
    appId: '1:43641634764:web:234599f57dd2624fe8e769',
    messagingSenderId: '43641634764',
    projectId: 'movie-app-fc8ff',
    authDomain: 'movie-app-fc8ff.firebaseapp.com',
    storageBucket: 'movie-app-fc8ff.firebasestorage.app',
    measurementId: 'G-FMZR0NV6QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JYvfnwr7Juo-V8wT6vOTva1uryYG9yA',
    appId: '1:43641634764:android:005a53262f4e7c50e8e769',
    messagingSenderId: '43641634764',
    projectId: 'movie-app-fc8ff',
    storageBucket: 'movie-app-fc8ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4TTgoHowVHL6pHdx0U0tMHih3Y9j5qg4',
    appId: '1:43641634764:ios:a30c493acead9dc1e8e769',
    messagingSenderId: '43641634764',
    projectId: 'movie-app-fc8ff',
    storageBucket: 'movie-app-fc8ff.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4TTgoHowVHL6pHdx0U0tMHih3Y9j5qg4',
    appId: '1:43641634764:ios:a30c493acead9dc1e8e769',
    messagingSenderId: '43641634764',
    projectId: 'movie-app-fc8ff',
    storageBucket: 'movie-app-fc8ff.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEpE5xaHwu_0r6O3ykMewCadB-1aW9zE4',
    appId: '1:43641634764:web:885f897cdfd44fece8e769',
    messagingSenderId: '43641634764',
    projectId: 'movie-app-fc8ff',
    authDomain: 'movie-app-fc8ff.firebaseapp.com',
    storageBucket: 'movie-app-fc8ff.firebasestorage.app',
    measurementId: 'G-EDQ1ZSJH1B',
  );
}
